name: Sync extension test

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/sync-extension-test.yml
      - workflow-templates/.github/workflows/*.yml

jobs:
  copy:
    strategy:
      matrix:
        repository:
          - AchievementBadges
          - DiscordRCFeed
          - FacetedCategory
          - FemiwikiSkin
          - PageViewInfoGA
          - Sanctions
          - UnifiedExtensionForFemiwiki
        branch:
          - main
          - REL1_39

    runs-on: ubuntu-latest
    steps:
      - uses: lens0021/create-other-repo-branch-action@main
        continue-on-error: true # Errors when the name of the branch is already used
        with:
          repository_owner: ${{ github.repository_owner }}
          repository_name: ${{ matrix.repository }}
          new_branch_name: ${{ matrix.branch }}-update-extension-test
          new_branch_ref: origin/${{ matrix.branch }}
          access_token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Copycat
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: workflow-templates/.github/workflows/.
          src_branch: main
          dst_path: .github/workflows/.
          dst_owner: femiwiki
          dst_repo_name: ${{ matrix.repository }}
          dst_branch: ${{ matrix.branch }}-update-extension-test
          username: femiwiki-bot
          email: femiwiki-bot@users.noreply.github.com
          commit_message: |
            ${{ github.event.head_commit.message }}

            from https://github.com/${{ github.event.repository.full_name }}/commit/${{ github.event.head_commit.id }}
